language: php

branches:
  only:
    - master

php:
  - 7.2
  - 7.4

env:
  global:
    - DEFAULT=1

matrix:
  fast_finish: true

  include:
    - php: 7.4
      env: PHPCS=1 DEFAULT=0
    - php: 7.4
      env: PHPSTAN=1 DEFAULT=0

install:
  - composer install --no-interaction

script:
  - if [[ $DEFAULT = 1 ]]; then composer test; fi
  - if [[ $PHPCS = 1 ]]; then composer cs-check; fi
  - if [[ $PHPSTAN = 1 ]]; then composer analyse; fi

notifications:
  email: false
